# **[Python] - [Introdução ao NumPy]**
**Plataforma: DataCamp**

**Data: 2026-06-17**

**Status: Em andamento**

## **📚 Objetivo desta aula**

*Entender o que são Arrays do NumPy e por que eles são muito mais rápidos e eficientes para cálculos matemáticos do que as listas nativas do Python.*

## **1️⃣ Conceito Teórico**
**O que é?**

*O NumPy é uma biblioteca que introduz o objeto ndarray (n-dimensional array). Ao contrário de uma lista, que pode conter vários tipos de dados, o array do NumPy é otimizado para conter elementos de um único tipo (geralmente números), permitindo operações matemáticas em toda a estrutura de uma vez.*

**Por quê aprender?**

*Listas comuns do Python são lentas para cálculos grandes. O NumPy utiliza C "por baixo dos panos", o que torna as operações matemáticas milhares de vezes mais rápidas. É a base para o Pandas, Matplotlib e quase toda a Inteligência Artificial.*

In [4]:
import numpy as np

In [12]:
# Criando as listas
altura = [1.73, 1.68, 1.71, 1.89, 1.79]
peso = [65.4, 59.2, 63.6, 88.4, 68.7]

In [13]:
# Tranformando as listas em arrays
np_altura = np.array(altura)
np_altura

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [14]:
np_peso = np.array(peso)
np_peso

array([65.4, 59.2, 63.6, 88.4, 68.7])

In [15]:
# Fazendo o cáalculo de IMC
imc = np_peso / np_altura ** 2
imc

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])